name: first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome to ubuntu
          run: echo welcome to ubuntu
        - name: read file content
          run: cat README.md